# Directories to exclude
exclude-dirs:
  - SOMETHING

# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE

# Add github urls
community-templates:
  - https://github.com/0x727/ObserverWard
  - https://github.com/0xAwali/Blind-SSRF
  - https://github.com/0xPugazh/my-nuclei-templates
  - https://github.com/0xmaximus/final_freaking_nuclei_templates
  - https://github.com/1in9e/my-nuclei-templates
  - https://github.com/Akokonunes/Private-Nuclei-Templates
  - https://github.com/DoubleTakes/nuclei-templates
  - https://github.com/Elsfa7-110/mynuclei-templates
  - https://github.com/JoshMorrison99/url-based-nuclei-templates
  - https://github.com/KeepHowling/all_freaking_nuclei_templates
  - https://github.com/Lu3ky13/Authorization-Nuclei-Templates
  - https://github.com/MR-pentestGuy/nuclei-templates
  - https://github.com/NightRang3r/misc_nuclei_templates
  - https://github.com/Saimonkabir/Nuclei-Templates
  - https://github.com/Saptak9983/Nuclei-Template
  - https://github.com/SirBugs/Priv8-Nuclei-Templates
  - https://github.com/ayadim/Nuclei-bug-hunter

