# Directories to exclude
exclude-dirs:
  - SOMETHING

# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE

# Add github urls
community-templates:
  - https://github.com/0x727/ObserverWard
  - https://github.com/0xAwali/Blind-SSRF
  - https://github.com/0xAwali/Virtual-Host
  - https://github.com/0xPugazh/my-nuclei-templates
  - https://github.com/0xmaximus/final_freaking_nuclei_templates
  - https://github.com/1in9e/my-nuclei-templates
  - https://github.com/ARPSyndicate/kenzer-templates
  - https://github.com/Akokonunes/Private-Nuclei-Templates
  - https://github.com/Arvinthksrct/alltemplate
  - https://github.com/AshiqurEmon/nuclei_templates
  - https://github.com/CharanRayudu/Custom-Nuclei-Templates
  - https://github.com/DoubleTakes/nuclei-templates
  - https://github.com/Elsfa7-110/mynuclei-templates
  - https://github.com/ExpLangcn/NucleiTP
  - https://github.com/Harish4948/Nuclei-Templates
  - https://github.com/Hunt2behunter/nuclei-templates
  - https://github.com/Jagomeiister/nuclei-templates
  - https://github.com/JoshMorrison99/url-based-nuclei-templates
  - https://github.com/Kaue-Navarro/Templates-kaue-nuclei
  - https://github.com/KeepHowling/all_freaking_nuclei_templates
  - https://github.com/Lopseg/nuclei-c-templates
  - https://github.com/Lu3ky13/Authorization-Nuclei-Templates
  - https://github.com/MR-pentestGuy/nuclei-templates
  - https://github.com/NightRang3r/misc_nuclei_templates
  - https://github.com/NitinYadav00/My-Nuclei-Templates
  - https://github.com/Odayex/Random-Nuclei-Templates
  - https://github.com/PedroF-369/nuclei_templates
  - https://github.com/R-s0n/Custom_Vuln_Scan_Templates
  - https://github.com/Saimonkabir/Nuclei-Templates
  - https://github.com/Saptak9983/Nuclei-Template
  - https://github.com/SirAppSec/nuclei-template-generator-log4j
  - https://github.com/SirBugs/Priv8-Nuclei-Templates
  - https://github.com/Str1am/my-nuclei-templates
  - https://github.com/SumedhDawadi/Custom-Nuclei-Template
  - https://github.com/System00-Security/backflow
  - https://github.com/adampielak/nuclei-templates
  - https://github.com/aels/CVE-2022-37042
  - https://github.com/alexrydzak/rydzak-nuclei-templates
  - https://github.com/ayadim/Nuclei-bug-hunter
  - https://github.com/badboy-sft/badboy_17-Nuclei-Templates-Collection

