# Directories to exclude
exclude-dirs:
  - SOMETHING

# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE

# Add github urls
community-templates:
  - https://github.com/projectdiscovery/nuclei-templates.git
  - https://github.com/NightRang3r/misc_nuclei_templates
  - https://github.com/ayadim/Nuclei-bug-hunter

